# Model 1 - multi-view, simultaneous entry, reconstructing frames

With this particular model, we can reconstruct frames using both single-view inputs and multi-view inputs. The aim of the model is to be able to reconstruct motion across views, and so input one view and reconstruct in another. However, we can also recontruct the frames after projecting in all 5 views simultaneously. With this particular model, this seems to give the best estimation of what we can reconstruct, and also serves as method for scaling the single view loadings.
In summary, to reconstruct using the multi-view inputs, one simply projects the multi-view vectors into the space to determine the loadings on the components, multiplies the components by the loadings, and then sums across the components. Then add mu back in (as the PCA spaces are centered) and voila, this gives you reconstructed frames across all 5 views. 
To reconstruct all views from a single view, one can project in that single view, and essentially calculate the inner product between the frames and the portion of the components being projected onto (the portion of the components corresponding to the input view). This inner product can then be scaled, and then the same process can be applied as above to scale and sum the components to provide the reconstructions.


## Scaling
As one might expect, projecting a single view in only projects onto about one 5th of the PCA components (as there are 5 views) and as a result, the reconstructions made without any scaling contain very muted motion. The motion is there, but muted. However, if we multiply each of the loadings by 5 we end up with exaggerated motion. The reason for this can be observed when we look at the loadings from the multi-view reconstructions, which is a reason why they come in handy. By comparing the single-view loadings to the multi-view loadings, we can see that actually a non-uniform scaling is required. The early components needs to be scaled by a scale factor of close to 5, while the later components are scaled by a much smaller scaling factor. After trying to workout why this is, it turns out the later components are more specific to certain viewpoints, and so the motion in one view is not necessary consistent with motion in another view, and therefore some frames/views require a large scaling factor, and others a much smaller scaling factor, and as a result the desired scaling factor on average plateaus near x1.
To put it simply, scaling is a bit of a pain, and by no means perfect, but it has helped identify a potential problem.
